# ─────────────────────────────────────
# Font
# ─────────────────────────────────────

font_family      NotoSansMono Nerd Font
font_size        10.5

# ─────────────────────────────────────
# Window
# ─────────────────────────────────────

window_padding_width 10
draw_minimal_borders yes

hide_window_decorations yes

background_opacity 0.88
dynamic_background_opacity yes

background_blur 0

# ─────────────────────────────────────
# Abyss palette
# ─────────────────────────────────────

background            #081013
foreground            #c3d1cf

selection_background  #23383b
selection_foreground  #e2efec

cursor                 #e44932
cursor_text_color      #081013

url_color              #6fa9a6

color0  #0b1113
color8  #354548

color1  #b52b25
color9  #ef4938

color2  #557b70
color10 #72a595

color3  #a47a38
color11 #d4a64d

color4  #426b78
color12 #6095a3

color5  #79485d
color13 #a75f79

color6  #4d8d8b
color14 #6fc1bd

color7  #a7b6b4
color15 #dbe7e4

# ─────────────────────────────────────
# Tabs
# ─────────────────────────────────────

active_tab_foreground    #081013
active_tab_background    #b52b25

inactive_tab_foreground  #758684
inactive_tab_background  #101a1d

tab_bar_background       #081013
